apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: azuredevopsagenthafslund
spec:
  replicas: 6
  serviceName: azuredevopsagenthafslund
  selector:
    matchLabels:
      app: azuredevopsagenthafslund
  template:
    metadata:
      labels:
        app: azuredevopsagenthafslund
    spec:
      imagePullSecrets:
      - name: containerregistryprodsecret
      containers:
      - name: azuredevopsagenthafslund
        image: containerregistryprod.azurecr.io/azuredevopsagent:1.0.0
        env:
          - name: AZP_URL
            value: "https://dev.azure.com/hafslundnett"
          - name: AZP_POOL
            value: "AKS"
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azuredevopsagenthafslund
                key: token
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket-volume
        securityContext:
          privileged: true
      volumes:
        # This allows the pod to use the docker engine on the underlying node
        - name: docker-socket-volume
          hostPath:
            path: /var/run/docker.sock
            type: File

            