schedules:
- cron: "0 6-17 * * 1-5"
  displayName: At minute 0 past every hour from 6 through 17 on every day-of-week from Monday through Friday
  branches:
    include:
    - trunk
  always: true

trigger: none

pool: elvia

steps:
  - bash: echo "Ah, ha, ha, ha, stayin' alive, stayin' alive"
    displayName: Keep the elvia hosted agent alive
