trigger: none

pool: elvia-hosted-agent-dev

steps:
  - bash: df
    displayName: df
  - bash: curl http://ipinfo.io/json | jq '.'
    displayName: Get IP
  - bash: echo "Ah, ha, ha, ha, stayin' alive, stayin' alive"
    displayName: Keep the elvia-hosted-agent-dev agent alive
