apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: azuredevopsagentelvia
spec:
  replicas: 3
  serviceName: azuredevopsagentelvia
  selector:
    matchLabels:
      app: azuredevopsagentelvia
  template:
    metadata:
      labels:
        app: azuredevopsagentelvia
    spec:
      containers:
      - name: azuredevopsagentelvia
        image: containerregistryelvia.azurecr.io/azuredevopsagent:imagetag
        env:
          - name: AZP_URL
            value: "https://dev.azure.com/3lvia"
          - name: AZP_POOL
            value: "AKS"
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azuredevopsagentelvia
                key: token
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket-volume
        securityContext:
          privileged: true
      volumes:
        # This allows the pod to use the docker engine on the underlying node
        - name: docker-socket-volume
          hostPath:
            path: /var/run/docker.sock
            type: File
